### ISSUE TITLE
Mission - Click on a module and bring up the user's preferred manual for that module

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#34]
When browsing a mission, clicking on a module should bring up the user's preferred manual for that module.

**Comment by Luminoscity** [comment]
Basically impossible. That information is stored in localStorage on a user's browser and the localStorage is specific to each website. One website absolutely may not access the localStorage on your browser from a different website. And there are huge security reasons why they can't.
In short, we could pull up the original manual, but we can't pull up the preferred manual.

**Comment by Blananas2** [comment]
This might be a bit of a stretch but maybe the repo can add a feature where you can append something to the URL (similar to how you can put a number after a # to get ruleseeded versions of manuals) which will send you to the manual you prefer. While things will have to be done on the repo's side to implement this, it would be extremely useful for not just this site to use but any page that links to a manual.

**Comment by Luminoscity** [comment]
Hmm, well since websites are not allowed to access the localStorage on your browser put there by other websites, the only way I could think to make this work is to have the repo be able to export your preferred manuals. This would be kind of a hassle though as you would have to
1. Go to the repo and export your preferred manuals
2. Go to Sam's site and import your preferred manuals.
3. Repeat these steps any time you want sync your preferences stored on Sam's site with the ones stored on the repo.
Unfortunately there is no way to automate this as the repo can't just send over your preferences any time you ask for it as your preferences are stored on your browser, not on the repo's server, so the repo doesn't even have access to that info unless you are currently looking at the repo in the current tab.

This an annoying way to implement it I know, but if you really want this feature, we can do it that way.
What do you think @Blananas2 @rexkix ?

**Comment by samfundev** [comment]
I believe this has been implemented as best as possible with what's available on the repo. There's probably some discussion to be had about a better way to handle translated modules. There's no way for user's to pick a preferred manual for translated modules, so this would need to be expanded on the repo side.
