### ISSUE TITLE
Icons for modules are sometimes wrong

### ISSUE THREAD

**Issue by rexkix** [samfundev/KTANE-Bombs#4]
Icons for modules in missions are sometimes wrong.

For example, look at !uc and the module in the first row for The Cube:
Mission: https://bombs.samfun.dev/mission/!uc
Image: https://cdn.discordapp.com/attachments/474726058428727298/991217046077579325/unknown.png

It's really image for The Cruel Code.

**Comment by samfundev** [comment]
Reduce this from happening, the server will now refetch the repository information every hour.

**Comment by rexkix** [comment]
Is that why we saw it?  Our repo info was out of date?

**Comment by samfundev** [comment]
Yep, the repository information about where the icon was located was out of date. Since it's the server that caches that information, it needs to clear the cache to fix the problem.

**Comment by rexkix** [comment]
Aren't icons associated with modules based on an unchanging module ID?

**Comment by samfundev** [comment]
We do find the icon position based on the module ID. Icons are loaded via a [spritesheet](https://ktane.timwi.de/iconsprite), the position in the spritesheet comes from the repository information.

**Comment by rexkix** [comment]
Why not cache the position info and spritesheet a the same time?

**Comment by samfundev** [comment]
I could cache the spritesheet on the server, but if do that I don't I believe it would reuse the cache from the repository. Plus, I did have an idea about how the repo can significantly reduce the chance that the positions of icons would change. [Which Timwi has implemented.](https://github.com/Timwi/KtaneWeb/commit/4173ec47d3aaa4b4db6db625af7c28f70dcf2ee9) So I'm a bit torn between the benefit of being able to reuse the cache from the repo (meaning the spritesheet will load instantly) or having perfectly accurate module icons (but the cache might not be there for our spritesheet). Especially since those icons are much less likely to be wrong.
