### ISSUE TITLE
Add "Has Solo Solve" to filters

### ISSUE THREAD

**Issue by BlvdBroken** [samfundev/KTANE-Bombs#99]
Title

**Comment by Luminoscity** [comment]
@BlvdBroken When I implement this, you are specifically wanting the Has Team/EFM Solve filter option to longer count solos, right? So that if you had the top two set to Yes, this mission would not show up because it does not have both Team/EFM and Solo: 
![image](https://github.com/samfundev/KTANE-Bombs/assets/10985005/93552a1c-e229-4af8-9efb-198ebb22fbaa)
